name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Server
        run: |
          # Comandos de despliegue, como subir archivos a un servidor
          # o hacer un push a Glitch
          python deploy.py  # Reemplaza esto con tus comandos específicos
        env:
          YOUR_SECRET: ${{ secrets.YOUR_SECRET }}
